### ISSUE TITLE
Issue with the latest Google

### ISSUE THREAD

**Issue by seriaati** [wdzeng/the-content-farm-terminator#25]
Extension enabled:

![image](https://user-images.githubusercontent.com/61446626/220112926-0c02732b-f6b5-477d-bc85-1190d0b2aaae.png)

Extension disabled:

![image](https://user-images.githubusercontent.com/61446626/220112873-a41a0b83-c73e-4360-a80f-eaf93b8d9953.png)

**Comment by wdzeng** [comment]
Thanks for the report!
