### ISSUE TITLE
Question: Are blocked sites reported to web safety sites

### ISSUE THREAD

**Issue by nicoleahmed** [wdzeng/the-content-farm-terminator#32]
Hi 
Great work tackling the annoying issue of content farms

I wasn't sure what is meant by terminator.

When sites are marked as content farms using the extension is there a report sent to any web safety sites? Like netcraft, abuseipdb, www.scamadviser.com, safeweb.norton.com etc

I think doing this would be amazing

**Comment by wdzeng** [comment]
Hi,

Thanks for supporting my extension :)

The extension does not collect or send any data. Therefore nothing is sent to anywhere.
